Import h5py library

In [1]:
# Prerequisites
import numpy as np
import h5py

## Create a File and Dataset

In [18]:
FILE_NAME = "my_file_1.hdf5"

# Create a HDF5 file
with h5py.File(FILE_NAME, "w") as f:

    # Create some datasets with data and attributes
    dset1 = f.create_dataset("my_dataset_5x5", (5,5), dtype="f")
    dset1.attrs["description"] = "5x5 zero array"

    my_data = np.arange(100).reshape(10, 10)
    dset2 = f.create_dataset("my_dataset_10x10", data=my_data)
    dset2.attrs["description"] = "10x10 matrix of ints countint up"
    dset2.attrs["unit"] = "unitless"

    my_random_data = np.random.random((5,5))
    dset3 = f.create_dataset("my_random_data", data=my_random_data)
    dset3.attrs["description"] = "5x5 matrix of random floats"
    dset3.attrs["unit"] = "whatever"

    # Create a group and place dataset into the group
    group = f.create_group("my_group")
    dset4 = group.create_dataset("group_data_1", data = np.linspace(0, 1, 10))
    dset5 = group.create_dataset("group_data_2", data = np.linspace(0, 5, 10))
    group.attrs["group name"] = "Group 1"

print(f"File '{FILE_NAME}' written.")

File 'my_file_1.hdf5' written.


## Open a File and Retrieve the dataset 

In [19]:
with h5py.File(FILE_NAME, "r") as hdf:
    print(f"Keys: {list(hdf.keys())}\n")

    # Read and print attribytes
    for key in list(hdf.keys()):
        print(f"{key} has attributes {list(hdf[key].attrs.keys())}")
    print()

    # my_ramndom_data attributes
    for key in list(hdf["my_random_data"].attrs.keys()):
        print(f"'my_random_data' attribute '{key}' = '{hdf["my_random_data"].attrs[key]}'")
    print()

    data = hdf["my_random_data"][:]
    print("'my_random_data': \n", data)


Keys: ['my_dataset_10x10', 'my_dataset_5x5', 'my_group', 'my_random_data']

my_dataset_10x10 has attributes ['description', 'unit']
my_dataset_5x5 has attributes ['description']
my_group has attributes ['group name']
my_random_data has attributes ['description', 'unit']

'my_random_data' attribute 'description' = '5x5 matrix of random floats'
'my_random_data' attribute 'unit' = 'whatever'

'my_random_data': 
 [[0.0549704  0.16498058 0.46219032 0.12181974 0.07030152]
 [0.13616488 0.83192259 0.23325601 0.34312248 0.66461632]
 [0.46967892 0.55694846 0.15837602 0.90175336 0.11154696]
 [0.68691651 0.25615483 0.1054686  0.91008987 0.87362771]
 [0.71230158 0.90764462 0.73648294 0.65670038 0.03076782]]
