# Numpy 101

In [2]:
# Prerequisites
import numpy as np

## Using Numpy Arrays for point clouds

In [6]:
array1 = np.array([[0,0,0],[1,1,1],[2,2,2]]) 
print(type(array1))
print(array1)

&lt;class &#39;numpy.ndarray&#39;&gt;
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [7]:
array2 = np.array([[3,3,3],[4,4,4],[5,5,5]]) 
print(type(array2))
print(array2)

&lt;class &#39;numpy.ndarray&#39;&gt;
[[3 3 3]
 [4 4 4]
 [5 5 5]]


In [15]:
# Adding Arrays does a matrix addition
array = array1 + array2
print(type(array))
print(array)
print(array.shape)

&lt;class &#39;numpy.ndarray&#39;&gt;
[[3 3 3]
 [5 5 5]
 [7 7 7]]
(3, 3)


## Concatenate arrays (merging 2 point clouds together)


In [18]:
np.concatenate((array1, array2), axis=0)
print(f"Array type: {type(array1)}")
print(f"Array shape: {array1.shape}")
print(array1)


&lt;class &#39;numpy.ndarray&#39;&gt;
[[3 3 3]
 [5 5 5]
 [7 7 7]]
(3, 3)
