# Numpy 101

(my "datascience" conda environment)

In [1]:
# Prerequisites
import numpy as np

## Initializing Array

In [2]:
# Initialize with list comprehension and range()
array = []
array = [i for i in range(10)]
print(array)



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
# Min and Max values
array = np.array([i for i in range(12)])
print(array)
print("Shape: ", array.shape)
print("Min value: ", array.min())
print("Max value: ", array.max())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape:  (12,)
Min value:  0
Max value:  11


In [5]:
# initialize array with arange
array2 = np.arange(12)
print(array2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
# change to 2-dimensional array
#array2d = np.reshape(array2, (3,4))
array2d = array2.reshape((3,4))
array2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
# change to 3-dimensional array
array3d = array2.reshape((2,2,3))
array3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [20]:
# Create a numpy array from a Python List
list = [5,4,3,2,1,0]
type(list)

list

In [21]:
array3 = np.asarray(list, dtype=object)
array3

array([5, 4, 3, 2, 1, 0], dtype=object)

In [22]:
type(array3)

numpy.ndarray

# Create array from an image

In [10]:
# Prerequisites
import cv2

In [15]:
im_gray = cv2.imread("images/image_8x8.jpg",0)  # 0 = read as gray scale. 1 = read as BGR
im_gray

array([[ 92,  92,  94,  87, 179, 172, 174, 174],
       [ 94,  92,  93,  90, 182, 178, 180, 178],
       [ 95,  92,  92,  91, 175, 174, 174, 171],
       [ 88,  88,  94,  98, 173, 177, 182, 183],
       [185, 183, 180, 168, 206, 193, 190, 188],
       [178, 180, 182, 175, 203, 196, 198, 201],
       [179, 180, 181, 176, 196, 191, 192, 194],
       [180, 180, 180, 179, 199, 198, 198, 198]], dtype=uint8)

In [16]:
im_rgb = cv2.imread("images/image_8x8.jpg",1)  # 0 = read as gray scale. 1 = read as BGR
im_rgb

array([[[ 92,  92,  92],
        [ 92,  92,  92],
        [ 94,  94,  94],
        [ 87,  87,  87],
        [179, 179, 179],
        [172, 172, 172],
        [174, 174, 174],
        [174, 174, 174]],

       [[ 94,  94,  94],
        [ 92,  92,  92],
        [ 93,  93,  93],
        [ 90,  90,  90],
        [182, 182, 182],
        [178, 178, 178],
        [180, 180, 180],
        [178, 178, 178]],

       [[ 95,  95,  95],
        [ 92,  92,  92],
        [ 92,  92,  92],
        [ 91,  91,  91],
        [175, 175, 175],
        [174, 174, 174],
        [174, 174, 174],
        [171, 171, 171]],

       [[ 88,  88,  88],
        [ 88,  88,  88],
        [ 94,  94,  94],
        [ 98,  98,  98],
        [173, 173, 173],
        [177, 177, 177],
        [182, 182, 182],
        [183, 183, 183]],

       [[185, 185, 185],
        [183, 183, 183],
        [180, 180, 180],
        [168, 168, 168],
        [206, 206, 206],
        [193, 193, 193],
        [190, 190, 190],
        [188, 188

In [17]:
# Write to file
cv2.imwrite("images/new_image_8x8.png", im_gray)

True

# Min and Max values
print(:)

In [3]:
# Initialize as numpy array
import numpy as np 
array = np.empty(10, dtype=object)
print(array) 

[None None None None None None None None None None]


In [4]:
# Direct initialization as Python 
array_int = [7] * 10
print(array_int)
array_str = ["Hello"] * 10
print(array_str)

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
['Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello']


In [5]:
# Initialize multi-dimensional RGB color array
array_rgb = [[255, 127, 36]] * 10
print(array_rgb)

[[255, 127, 36], [255, 127, 36], [255, 127, 36], [255, 127, 36], [255, 127, 36], [255, 127, 36], [255, 127, 36], [255, 127, 36], [255, 127, 36], [255, 127, 36]]


## Using Numpy Arrays for point clouds

In [2]:
array1 = np.array([[0,0,0],[1,1,1],[2,2,2]]) 
print(type(array1))
print(array1)

<class 'numpy.ndarray'>
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [3]:
array2 = np.array([[3,3,3],[4,4,4],[5,5,5]]) 
print(type(array2))
print(array2)

<class 'numpy.ndarray'>
[[3 3 3]
 [4 4 4]
 [5 5 5]]


In [4]:
# Adding 2 Arrays performs a matrix addition
array = array1 + array2
print(type(array))
print(array)
print(array.shape)

<class 'numpy.ndarray'>
[[3 3 3]
 [5 5 5]
 [7 7 7]]
(3, 3)


## Concatenate arrays (merging 2 point clouds together)


In [6]:
array = np.concatenate((array1, array2), axis=0)
print(f"Array type: {type(array)}")
print(f"Array shape: {array.shape}")
print(array)


Array type: <class 'numpy.ndarray'>
Array shape: (6, 3)
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]


## Delete Rows or Columns

In [9]:
    array = np.arange(12).reshape(3, 4)
    print("array:")
    print(array)
    # [[ 0  1  2  3]
    #  [ 4  5  6  7]
    #  [ 8  9 10 11]]
    print("shape:")
    print(array.shape)

array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape:
(3, 4)


In [10]:
# Delete last row
row_del = np.delete(array, 2, 0)
print(row_del)
# [[ 0  1  2  3]
#  [ 4  5 6 7]]
print("shape:")
print(row_del.shape)

[[0 1 2 3]
 [4 5 6 7]]
shape:
(2, 4)


In [11]:
# Delete last column
col_del = np.delete(array, 3, axis=1)
print(col_del)
# [[ 0  1  2]
#  [ 4  5  6]
#  [ 8  9 10]]
print("shape:")
print(col_del.shape)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
shape:
(3, 3)


## Splitting Array

In [5]:
# Split 1D Array
import numpy as np 
array = np.arange(10)
print(array)
new_array = np.split(array, 5)
print(new_array)

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [7]:
# Split 2D Array
array = np.arange(16).reshape(4, 4)
print(array)
new_array = np.array_split(array,3)
print(new_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [13]:
# Split array by columns with hsplit
array = np.arange(16).reshape(4, 4)
print(array)
# Split the array at column index 2
(array1, array2) = np.hsplit(array, 2)
print(array1)
print(array1.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
(4, 2)


In [16]:
# Split array by columns with hsplit
array = np.arange(16).reshape(4, 4)
print(array)
# Split column index 3 to separate array
(array1, array2) = np.hsplit(array, [3])
print("array1:")
print(array1)
print(array1.shape)
print("array2:")
print(type(array2))
print(array2)
print(array2.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
array1:
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
(4, 3)
array2:
<class 'numpy.ndarray'>
[[ 3]
 [ 7]
 [11]
 [15]]
(4, 1)


## Squeeze, remove redundant dimensions of array

In [11]:
# Split array by columns with hsplit
array = np.arange(16).reshape(4, 4)
print(array)
# Split column index 3 to separate array
(array1, _) = np.hsplit(array, [1])
print("array1:")
print(array1)
print("array1 shape: ", array1.shape)
list1 = np.squeeze(array1)
print("list1:")
print(list1)
print("list1 shape: ", list1.shape)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
array1:
[[ 0]
 [ 4]
 [ 8]
 [12]]
array1 shape:  (4, 1)
list1:
[ 0  4  8 12]
list1 shape:  (4,)


## Stacking Arrays

In [23]:
import numpy as np 

a = np.arange(6)
print("a: ", a)
b = np.arange(start=6, stop=12, step=1)
print("b: ", b)
c = np.arange(start=12, stop=18, step=1)
print("c: ", c)

# Stack Normally
stack_1 = np.stack((a, b, c))
print("Stack 1:\n", stack_1)

# Stack "Vertically"
stack_2 = np.stack((a, b, c), axis=-1)
print("Stack 2:\n", stack_2)

a:  [0 1 2 3 4 5]
b:  [ 6  7  8  9 10 11]
c:  [12 13 14 15 16 17]
Stack 1:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
Stack 2:
 [[ 0  6 12]
 [ 1  7 13]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]]
