# Numpy 101

In [1]:
# Prerequisites
import numpy as np

## Initializing Array

In [2]:
# Initialize with loop and range()
array = []
array = [7 for i in range(10)]
print(array)


[7, 7, 7, 7, 7, 7, 7, 7, 7, 7]


In [3]:
# Initialize as numpy array
import numpy as np 
array = np.empty(10, dtype=object)
print(array) 

[None None None None None None None None None None]


In [4]:
# Direct initialization as Python 
array_int = [7] * 10
print(array_int)
array_str = ["Hello"] * 10
print(array_str)

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
['Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello']


In [5]:
# Initialize multi-dimensional RGB color array
array_rgb = [[255, 127, 36]] * 10
print(array_rgb)

[[255, 127, 36], [255, 127, 36], [255, 127, 36], [255, 127, 36], [255, 127, 36], [255, 127, 36], [255, 127, 36], [255, 127, 36], [255, 127, 36], [255, 127, 36]]


## Using Numpy Arrays for point clouds

In [2]:
array1 = np.array([[0,0,0],[1,1,1],[2,2,2]]) 
print(type(array1))
print(array1)

<class 'numpy.ndarray'>
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [3]:
array2 = np.array([[3,3,3],[4,4,4],[5,5,5]]) 
print(type(array2))
print(array2)

<class 'numpy.ndarray'>
[[3 3 3]
 [4 4 4]
 [5 5 5]]


In [4]:
# Adding 2 Arrays performs a matrix addition
array = array1 + array2
print(type(array))
print(array)
print(array.shape)

<class 'numpy.ndarray'>
[[3 3 3]
 [5 5 5]
 [7 7 7]]
(3, 3)


## Concatenate arrays (merging 2 point clouds together)


In [6]:
array = np.concatenate((array1, array2), axis=0)
print(f"Array type: {type(array)}")
print(f"Array shape: {array.shape}")
print(array)


Array type: <class 'numpy.ndarray'>
Array shape: (6, 3)
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]


## Delete Rows or Columns

In [9]:
    array = np.arange(12).reshape(3, 4)
    print("array:")
    print(array)
    # [[ 0  1  2  3]
    #  [ 4  5  6  7]
    #  [ 8  9 10 11]]
    print("shape:")
    print(array.shape)

array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape:
(3, 4)


In [10]:
# Delete last row
row_del = np.delete(array, 2, 0)
print(row_del)
# [[ 0  1  2  3]
#  [ 4  5 6 7]]
print("shape:")
print(row_del.shape)

[[0 1 2 3]
 [4 5 6 7]]
shape:
(2, 4)


In [11]:
# Delete last column
col_del = np.delete(array, 3, axis=1)
print(col_del)
# [[ 0  1  2]
#  [ 4  5  6]
#  [ 8  9 10]]
print("shape:")
print(col_del.shape)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
shape:
(3, 3)


## Splitting Array

In [5]:
# Split 1D Array
import numpy as np 
array = np.arange(10)
print(array)
new_array = np.split(array, 5)
print(new_array)

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [7]:
# Split 2D Array
array = np.arange(16).reshape(4, 4)
print(array)
new_array = np.array_split(array,3)
print(new_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [13]:
# Split array by columns with hsplit
array = np.arange(16).reshape(4, 4)
print(array)
# Split the array at column index 2
(array1, array2) = np.hsplit(array, 2)
print(array1)
print(array1.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
(4, 2)


In [16]:
# Split array by columns with hsplit
array = np.arange(16).reshape(4, 4)
print(array)
# Split column index 3 to separate array
(array1, array2) = np.hsplit(array, [3])
print("array1:")
print(array1)
print(array1.shape)
print("array2:")
print(type(array2))
print(array2)
print(array2.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
array1:
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
(4, 3)
array2:
<class 'numpy.ndarray'>
[[ 3]
 [ 7]
 [11]
 [15]]
(4, 1)
