# Numpy 101

In [3]:
# Prerequisites
import numpy as np

## Using Numpy Arrays for point clouds

In [2]:
array1 = np.array([[0,0,0],[1,1,1],[2,2,2]]) 
print(type(array1))
print(array1)

<class 'numpy.ndarray'>
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [3]:
array2 = np.array([[3,3,3],[4,4,4],[5,5,5]]) 
print(type(array2))
print(array2)

<class 'numpy.ndarray'>
[[3 3 3]
 [4 4 4]
 [5 5 5]]


In [4]:
# Adding Arrays does a matrix addition
array = array1 + array2
print(type(array))
print(array)
print(array.shape)

<class 'numpy.ndarray'>
[[3 3 3]
 [5 5 5]
 [7 7 7]]
(3, 3)


## Concatenate arrays (merging 2 point clouds together)


In [6]:
array = np.concatenate((array1, array2), axis=0)
print(f"Array type: {type(array)}")
print(f"Array shape: {array.shape}")
print(array)


Array type: <class 'numpy.ndarray'>
Array shape: (6, 3)
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]


## Delete Rows or Columns

In [9]:
    array = np.arange(12).reshape(3, 4)
    print("array:")
    print(array)
    # [[ 0  1  2  3]
    #  [ 4  5  6  7]
    #  [ 8  9 10 11]]
    print("shape:")
    print(array.shape)

array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape:
(3, 4)


In [10]:
# Delete last row
row_del = np.delete(array, 2, 0)
print(row_del)
# [[ 0  1  2  3]
#  [ 4  5 6 7]]
print("shape:")
print(row_del.shape)

[[0 1 2 3]
 [4 5 6 7]]
shape:
(2, 4)


In [11]:
# Delete last column
col_del = np.delete(array, 3, axis=1)
print(col_del)
# [[ 0  1  2]
#  [ 4  5  6]
#  [ 8  9 10]]
print("shape:")
print(col_del.shape)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
shape:
(3, 3)
